apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-cert
  namespace: istio-ingress
spec:
  secretName: manager-cacerts
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - killercoda.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - localhost
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager