apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-v1
  labels:
    app: follow
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow
      version: v1
  template:
    metadata:
      labels:
        app: follow
        version: v1
    spec:
      serviceAccountName: mock-follow
      containers:
      - name: follow
        image: nicholasjackson/fake-service:v0.24.2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
        resources:
          requests:
            memory: "60Mi"
            cpu: "250m"
            # ephemeral-storage: "0Mi" # lab cannot
          limits:
            memory: "100Mi"
            cpu: "500m"
            # ephemeral-storage: "0Mi" # lab cannot
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 10001
          # runAsGroup: 10001
          # runAsNonRoot: true
          # readOnlyRootFilesystem: true
        ports:
        - containerPort: 9080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9080"
        - name: "UPSTREAM_URIS"
          value: "http://greetings:9080"
        - name: "NAME"
          value: "follow"
        - name: "MESSAGE"
          value: "---- BEGIN API -----"
---
apiVersion: v1
kind: Service
metadata:
  name: follow
  labels:
    app: follow
    service: follow
spec:
  selector:
    app: follow
  ports:
  - name: http
    protocol: TCP
    port: 9080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mock-follow
  labels:
    account: follow
