apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - "*"
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: sa-external-services
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - http-gateway                      # 1
#   http:
#   - match:
#     - uri:
#         exact: /
#     # - uri:
#     #     prefix: /static
#     # - uri:
#     #     regex: '^.*\.(ico|png|jpg)$'
#     route:
#     - destination:
#         host: sa-frontend             # 2
#         port:
#           number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-api-external-service
spec:
  hosts:
  - "*" #"backend-api.istio-lab-01.svc.cluster.local"
  gateways:
  - istio-ingress/mock-apps-gateway # <namespace>/<name> format
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: backend-api
        port:
          number: 8080