apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gw-install
spec:
  profile: empty
  values:
    gateways:
      ingress-demo:
        autoscaleEnabled: false
        namespaceSelector:
            matchLabels:
              istio: istio-ingress
        # resources:
        #   requests:
        #     cpu: 500m
        #     memory: 512Mi
        #   limits:
        #     cpu: 2
        #     memory: 2Gi
  components:
    ingressGateways:
    - name: ingress-demo
      namespace: istio-ingress
      enabled: true
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: ingress-demo
          patches:
          - path: spec.template.spec.containers[name:istio-proxy].lifecycle
            value:
              preStop:
                exec:
                  command: ["sh", "-c", "sleep 5"]