apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gw-install
spec:
  profile: empty
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        # resources:
        #   requests:
        #     cpu: 500m
        #     memory: 512Mi
        #   limits:
        #     cpu: 2
        #     memory: 2Gi
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: false
    - name: istio-ingressgateway2
      namespace: istio-ingress
      enabled: true
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway2
          patches:
          - path: spec.template.spec.containers[name:istio-proxy].lifecycle
            value:
              preStop:
                exec:
                  command: ["sh", "-c", "sleep 5"]