apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoyproxy
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
    service: envoy
spec:
  ports:
  - name: http
    port: 80
    targetPort: 15001
  selector:
    app: envoy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      serviceAccountName: envoyproxy      
      containers:
      - image: docker.io/envoyproxy/envoy:v1.24.1@sha256:46ca1ee2d0e3c45c1891b3e0508146e67a6fbdeea0e44b79d3e4b5c80287719a
        imagePullPolicy: IfNotPresent
        name: envoy
        command: 
          - "/usr/local/bin/envoy"
        args:
          - "--config-path /etc/envoy/envoy.yaml"
        ports:
        - containerPort: 15001
        volumeMounts:
          - name: envoy
            mountPath: /etc/envoy
      volumes:
        - name: envoy
          configMap:
            name: envoy