apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1
  labels:
    app: order-v1
spec:
  replicas: 1
  selector:
    matchLabels:
        app: order
        version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
      annotations:
    spec:
      serviceAccountName: order    
      containers:
      - name: order
        image: nicholasjackson/fake-service:v0.24.2@sha256:85f4ea8015a9ece18f5dbec7f68cb3480e22d8e772fbf2ca823559defcae1013
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "NAME"
          value: "order-v1"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "----> Order v1"
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080