
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
      version: v1
  template:
    metadata:
      labels:
        app: backend-api
        version: v1
    spec:
      serviceAccountName: backend-api
      containers:
      - name: backend-api
        image: nicholasjackson/fake-service:v0.24.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "UPSTREAM_URIS"
          value: "http://greetings:8080"
        - name: "NAME"
          value: "backend-api"
        - name: "MESSAGE"
          value: "----> API"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  selector:
    app: backend-api
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080