apiVersion: v1
kind: ServiceAccount
metadata:
  name: greetings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
  labels:
    app: greetings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
      version: v1
  template:
    metadata:
      labels:
        app: greetings
        version: v1
    spec:
      serviceAccountName: greetings    
      containers:
      - name: greetings
        image: nicholasjackson/fake-service:v0.24.2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        resources:
          requests:
            memory: "60Mi"
            cpu: "250m"
            # ephemeral-storage: "0Mi" # lab cannot
          limits:
            memory: "100Mi"
            cpu: "500m"
            # ephemeral-storage: "0Mi" # lab cannot
        securityContext:
          allowPrivilegeEscalation: false
          # runAsUser: 10001
          # runAsGroup: 10001
          # runAsNonRoot: true
          # readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "UPSTREAM_URIS"
          value: "http://order:8080"
        - name: "NAME"
          value: "greetings"
        - name: "MESSAGE"
          value: "---> Greetings!"

---
apiVersion: v1
kind: Service
metadata:
  name: greetings
spec:
  selector:
    app: greetings
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080