apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1
  labels:
    app: order-v1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
        app: order
        version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      serviceAccountName: mock-order    
      containers:
      - name: order
        image: nicholasjackson/fake-service:v0.24.2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
        resources:
          requests:
            memory: "60Mi"
            cpu: "250m"
            # ephemeral-storage: "0Mi" # lab cannot
          limits:
            memory: "100Mi"
            cpu: "500m"
            # ephemeral-storage: "0Mi" # lab cannot
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 10001
          # runAsGroup: 10001
          # runAsNonRoot: true
          # readOnlyRootFilesystem: true
        ports:
        - containerPort: 9080
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9080"
        - name: "NAME"
          value: "order-v1"
        - name: "SERVER_TYPE"
          value: "http"
        - name: "MESSAGE"
          value: "----> Order v1"
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
    service: order
spec:
  selector:
    app: order
  ports:
  - name: http
    protocol: TCP
    port: 9080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mock-order
  labels:
    account: order